# Values are "exported" to glsl, see RDPQMaterialsRenderEngine.init_shader

VALID_IN_TEX0 = 1 << 0
VALID_IN_UV = 1 << 1
VALID_IN_COMBINER = 1 << 2
VALID_IN_COMBINER_REG_K4 = 1 << 3
VALID_IN_COMBINER_REG_K5 = 1 << 4
VALID_IN_COMBINER_REG_PRIM_LOD_FRAC = 1 << 5
VALID_IN_COMBINER_REG_ENV = 1 << 6
VALID_IN_COMBINER_REG_PRIM = 1 << 7

# Each combiner slot value is given 5 bits
# _WORD is the int in which the value is stored (0 is .x, 1 is .y, ...)
# _SHIFT is the shift of the value inside the int
COMBINER_MASK = 0x1F
COMBINER_RGB_2A_SUBA_WORD = 0
COMBINER_RGB_2A_SUBA_SHIFT = 0
COMBINER_RGB_2A_SUBB_WORD = 0
COMBINER_RGB_2A_SUBB_SHIFT = 5
COMBINER_RGB_2A_MUL_WORD = 0
COMBINER_RGB_2A_MUL_SHIFT = 10
COMBINER_RGB_2A_ADD_WORD = 0
COMBINER_RGB_2A_ADD_SHIFT = 15
COMBINER_RGB_2B_SUBA_WORD = 0
COMBINER_RGB_2B_SUBA_SHIFT = 20
COMBINER_RGB_2B_SUBB_WORD = 0
COMBINER_RGB_2B_SUBB_SHIFT = 25
COMBINER_RGB_2B_MUL_WORD = 1
COMBINER_RGB_2B_MUL_SHIFT = 0
COMBINER_RGB_2B_ADD_WORD = 1
COMBINER_RGB_2B_ADD_SHIFT = 5

COMBINER_0 = 0
COMBINER_1 = 1
COMBINER_ENV = 2
COMBINER_ENV_ALPHA = 3
COMBINER_K4 = 4
COMBINER_K5 = 5
COMBINER_KEYCENTER = 6
COMBINER_KEYSCALE = 7
COMBINER_LOD_FRAC = 8
COMBINER_NOISE = 9
COMBINER_PRIM = 10
COMBINER_PRIM_ALPHA = 11
COMBINER_PRIM_LOD_FRAC = 12
COMBINER_SHADE = 13
COMBINER_SHADE_ALPHA = 14
COMBINER_TEX0 = 15
COMBINER_TEX0_ALPHA = 16
COMBINER_TEX1 = 17
COMBINER_TEX1_ALPHA = 18
COMBINER_COMBINED = 19
